apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:8.3.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_USERS_ALLOW_ORG_CREATE
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          value: /
        volumeMounts:
          - name: grafana-dashboard
            mountPath: /var/lib/grafana/dashboards
          - name: influxdb-dashboard-provisioning
            mountPath: /etc/grafana/provisioning/dashboards
          - name: influxdb-datasource-provisioning
            mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-dashboard
          configMap:
            name: grafana-dashboard
            defaultMode: 420
        - name: influxdb-dashboard-provisioning
          configMap:
            name: influxdb-dashboard-provisioning
            defaultMode: 420
        - name: influxdb-datasource-provisioning
          configMap:
            name: influxdb-datasource-provisioning
            defaultMode: 420





