apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-datasource-provisioning
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Influx-Jmeter
      type: influxdb
      access: proxy
      url: http://influxdb-svc:8086/
      database: jmeter
      user: admin
      password: admin
      isDefault: true
      editable: true