FROM kubernautslabs/jmeter-base:latest

LABEL org.opencontainers.image.created="12 January 2022"	
LABEL org.opencontainers.image.authors="adku44"	
LABEL org.opencontainers.image.revision="1.0"
		
EXPOSE 1099 50000
		
ENTRYPOINT $JMETER_HOME/bin/jmeter-server \
-Dserver.rmi.localport=50000 \
-Dserver_port=1099 \
-Jserver.rmi.ssl.disable=true
